### ISSUE TITLE
Installation Instructions from Cmd

### ISSUE THREAD

**Issue by Julie-Barelier** [NoraUi/noraui-archetype#14]
Hello Team,

I am trying to create a new NoraUI Project for another application.
So I did follow your steps within https://noraui.github.io/#installationInstructionsEclipse
But when I am running command to generate a maven archetype for NoraUI I always end up with error message  "The desired archetype does not exist com.github.noraui:noraui-archetype:3.3.0-SNAPSHOT"

Could you please help me on this part ?

Many thanks for your help.

Julie Barelier

**Comment by sgrillon14** [comment]
I update doc. Please use 3.2.0 in your archetype-catalog.xml file in your .m2 repository.

![archetype1](https://user-images.githubusercontent.com/5530550/64891650-d20a0a80-d672-11e9-839d-77ff3350be30.png)

If you want use V3.3.0-SNAPSHOT you need `git clone` this git repository and `clean install` this Maven project.

You can use [Maven command line](https://noraui.github.io/#installationInstructionsCmd). Everyday a new robot is generated and runned: https://github.com/NoraUi/noraui-archetype/blob/master/test/run.sh

full logs : https://travis-ci.org/NoraUi/noraui-archetype
