### ISSUE TITLE
problem with screen-recorder and Maven

### ISSUE THREAD

**Issue by JarekLipsko** [NoraUi/noraui-archetype#6]
[robot] $ /home/jenkins/tools/hudson.tasks.Maven_MavenInstallation/Apache_Maven_3.3.9/apache-maven-3.3.9/bin/mvn -gs /tmp/global-settings9196551290185328263.xml clean test -U "-Dcucumber.options=--tags '@LoginLogout'" -PpreIC,scenarioInitiator,ci,robot,postIC -Dmaven.test.failure.ignore=true
Picked up _JAVA_OPTIONS: -Djava.io.tmpdir=/home/jenkins/tmp -Djava.security.egd=file:/dev/./urandom
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building robot 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
Downloading: http://repo.jenkins-ci.org/releases/com/github/noraui/noraui/3.1.0/noraui-3.1.0.pom
Downloading: https://oss.sonatype.org/content/repositories/releases/com/github/noraui/noraui/3.1.0/noraui-3.1.0.pom
4/35 KB   
8/35 KB   
12/35 KB   
12/35 KB   
16/35 KB   
20/35 KB   
24/35 KB   
28/35 KB   
32/35 KB   
35/35 KB   
Downloaded: https://oss.sonatype.org/content/repositories/releases/com/github/noraui/noraui/3.1.0/noraui-3.1.0.pom (35 KB at 22.3 KB/sec)
Downloading: http://repo.jenkins-ci.org/releases/org/monte/screen-recorder/0.7.7/screen-recorder-0.7.7.pom          
Downloading: https://oss.sonatype.org/content/repositories/releases/org/monte/screen-recorder/0.7.7/screen-recorder-0.7.7.pom
Downloading: https://oss.sonatype.org/content/repositories/snapshots/org/monte/screen-recorder/0.7.7/screen-recorder-0.7.7.pom
Downloading: https://maven.oracle.com/org/monte/screen-recorder/0.7.7/screen-recorder-0.7.7.pom          
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE

**Comment by sgrillon14** [comment]
problem solve in version 3.1.1

**Comment by JarekLipsko** [comment]
problem solved for me in version 3.1.1
